name: salesiq_mobilisten
repository: https://github.com/AbdelhamidAhmedJeel/salesiq-mobilisten-flutter

packages:
  - packages/*
  - example/

commands:
  bootstrap:
    usePubspecOverrides: true
    runPubGet: true
    
  analyze:
    run: |
      dart analyze .
      dart format --set-exit-if-changed .
    description: Run analyzer and check formatting

  format:
    run: dart format .
    description: Format all code

  test:
    run: flutter test
    description: Run all tests
    packageFilters:
      dirExists: test

scripts:
  clean:all:
    run: melos run clean:flutter && melos run clean:packages
    description: Clean all build and cache files

  clean:flutter:
    run: flutter clean
    packageFilters:
      flutter: true

  clean:packages:
    run: dart pub cache clean
    packageFilters:
      dirExists: lib