name: salesiq_mobilisten

environment:
  sdk: '>=2.15.0 <4.0.0'

# Add these important fields
version: 1.0.0
description: Zoho SalesIQ SDK for Flutter
homepage: https://github.com/AbdelhamidAhmedJeel/salesiq-mobilisten-flutter

false_secrets:
  - example/**

dev_dependencies:
  melos: ^6.3.3
  flutter_lints: ^6.0.0

#workspace:
#  - packages/core
#  - packages/mobilisten
#  - packages/calls
#  - example
