name: Trigger Webhook for publishing package to pub.dev on Tag Creation

on:
  push:
    tags:
      - '*'

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug environment variables and context
        shell: cmd
        env:
          WEBHOOK_URL: ${{ secrets.SD_PUB_DEV_PUBLISHING_URL }}
          AUTH_TOKEN: ${{ secrets.SD_PUB_DEV_PUBLISHING_AUTH_TOKEN }}
        run: |
          example-command "%SD_PUB_DEV_PUBLISHING_URL%"      
          example-command "URL_Test: %secrets.SD_PUB_DEV_PUBLISHING_URL != ''%"

      - name: Send cURL request
        env:
          WEBHOOK_URL: ${{ secrets.SD_PUB_DEV_PUBLISHING_URL }}
          AUTH_TOKEN: ${{ secrets.SD_PUB_DEV_PUBLISHING_AUTH_TOKEN }}
        run: |          
          curl --manual--location --request POST 
          curl -X POST "$WEBHOOK_URL" \      
          -H "Authorization: $AUTH_TOKEN"
